package unmla.airport.ui.actions;

import javax.swing.AbstractAction;
import javax.swing.ImageIcon;

import unmla.airport.simul.Simulation;
import unmla.airport.simul.SimulationController;

/**
 * 
 */
public abstract class AbstractSimulationAction extends AbstractAction {

    /**
     * For serialization; generated by Eclipse.
     */
    private static final long serialVersionUID = 4088897218843835672L;
    
    /** */
    private final SimulationController  controller;
    
    /**
     * Constructor.
     * 
     * @param name
     * @param controller
     */
    public AbstractSimulationAction(final String name, 
                                    final SimulationController controller) {
        super(name);
        
        if(controller == null) {
            throw new NullPointerException();
        }
        
        this.controller = controller;
    }
    
    /**
     * 
     * @return
     */
    public SimulationController getController() {
        return this.controller;
    }
    
    /**
     * 
     * @return
     */
    public Simulation getSimulation() {
        return this.controller.getSimulation();
    }
    
    public final ImageIcon loadIcon(final String path) {
        return this.loadIcon(path, null);
    }
    
    public final ImageIcon loadIcon(final String path, 
                                    final String description) {
        if(path == null) {
            throw new NullPointerException();
        }
        
        return new ImageIcon(AbstractSimulationAction.class.getResource(path), 
                                description);
    }
}
