package unmla.airport.ui.actions;

import java.awt.event.ActionEvent;

import javax.swing.AbstractAction;

/**
 * 
 */
public class ExitSimulationAction extends AbstractAction {

    /**
     * For serialization; generated by Eclipse.
     */
    private static final long serialVersionUID = -6163376602228905615L;

    public ExitSimulationAction() {
        super("Exit");
    }
    
    @Override
    public void actionPerformed(ActionEvent e) {
        System.exit(0);
    }

}
