package unmla.airport.ui.actions;

import java.awt.event.ActionEvent;

import javax.swing.Action;

import unmla.airport.simul.SimulationController;
import unmla.airport.simul.command.ResetSimulationCommand;

/**
 * 
 */
public class ResetSimulationAction extends AbstractSimulationAction {
    
    /**
     * For serialization; generated by Eclipse.
     */
    private static final long serialVersionUID = 5782741586045893511L;

    /**
     * @param controller
     */
    public ResetSimulationAction(SimulationController controller) {
        super("Reset", controller);
        
        this.putValue(Action.LARGE_ICON_KEY, 
                this.loadIcon("/data/icons/reset.png", null));
        this.putValue(Action.SHORT_DESCRIPTION, "Stop and reset " +
        		                                "the simulation.");
        this.putValue(Action.SMALL_ICON, 
                this.loadIcon("/data/icons/resetSmall.png", null));
    }

    @Override
    public void actionPerformed(ActionEvent e) {
        final SimulationController controller = this.getController();
        
        controller.stop();
        controller.submitCommand(new ResetSimulationCommand());
        controller.getUiController()
                .getSettingsTabPane()
                .getOptionsPanel()
                .setEnabled(true);
    }
}
