package unmla.airport.graph.parser;

import java.util.HashMap;

import org.xml.sax.SAXException;

/**
 * 
 * @param S
 * @param T
 */
public class TypeFactory<S,T, V, E> extends HashMap<S, TypeCreator<T, V, E>> {

    /**
     * For serialization; generated by Eclipse.
     */
    private static final long serialVersionUID = 7927349747380033902L;
    
    /**
     * Constructor.
     */
    public TypeFactory() {
    }
    
    /**
     * 
     * @param id
     * @param dataList
     * @param attributes
     * @param names
     * @return
     * @throws IllegalStateException
     * @throws NullPointerException
     */
    public T create(final S id, final GraphMLParser<V, E> parser)
                    throws SAXException {
        if(id == null) {
            throw new NullPointerException();
        }
        
        if(parser == null) {
            throw new NullPointerException();
        }
        
        if(!this.containsKey(id)) {
            throw new IllegalStateException("No creator registered for: " + id);
        }
        
        final TypeCreator<T, V, E> creator = this.get(id);
        return creator.create(parser);
    }
}
