package unmla.airport.ui.tabpanes;

import java.awt.Dimension;

import javax.swing.JTabbedPane;

import unmla.airport.simul.SimulationController;
import unmla.airport.ui.panels.ConsolePanel;
import unmla.airport.ui.panels.LuggagePanel;

/**
 * 
 */
public class ConsoleTabPane extends JTabbedPane {

    /**
     * For serialization; generated by Eclipse.
     */
    private static final long serialVersionUID = 7468208372412093084L;

    private final ConsolePanel  consolePanel;
    
    private final LuggagePanel  luggagePanel;
    
    public ConsoleTabPane(final SimulationController controller) {
        super();
        
        if(controller == null) {
            throw new NullPointerException();
        }
        
        this.consolePanel = new ConsolePanel();
        this.luggagePanel = new LuggagePanel(controller);
        
        this.setPreferredSize(new Dimension(600, 175));
        this.addTab("Console", this.consolePanel);
        this.addTab("Luggage", this.luggagePanel);
        
        this.setSelectedIndex(1);
    }
    
    public LuggagePanel getLuggagePanel() {
        return this.luggagePanel;
    }
}
